name: JoshuaKim
favicon: null
layout_spectrum: 0.9467
typography_spectrum: 0.9006401284132153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5538079512771219
  lightness: 0.884021220728755
  saturation: 0.8143043161835521
  rhythmicContrast: 0.9601907881442457
purpose: []
